Big tests
CPP-KT/wordcount-task pull request #1
Opened 2022-02-17 17:39 UTC by Tindarid

2022-02-17 18:33 UTC, Dogzik requested changes
А что по поводу новых скриптов для гита?

2022-02-17 18:33 UTC, Dogzik commented on test.py
> +        big_chunk = rand_spaces(1) + rand_string(chunk_size, ' ')
Кажется так никогда не будет 0 пробелов в начале

2022-02-17 18:33 UTC, Dogzik commented on test.py
> +test_all_spaces(2 ** 32 + 42)
Я не уверен, что в питоне возведение в степерь имеет больший приоритет)

2022-02-17 18:57 UTC, Tindarid commented on test.py
> +test_all_spaces(2 ** 32 + 42)
Имеет)

2022-02-17 18:58 UTC, Tindarid commented on test.py
> +        big_chunk = rand_spaces(1) + rand_string(chunk_size, ' ')
Мне кажется в большом тесте это не важно

2022-02-18 13:56 UTC, Dogzik approved these changes

2022-02-18 13:57 UTC, merged